### ISSUE TITLE
HTTP/S Protocol (for all sites)

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#13]
We need to have SSL for the entire site, shop and CMS.

- [x] Redirect on the http server level
- [x] Update admin accordingly
- [x] Find and replace http to https

**Comment by nirgoldberg** [comment]
Done for the following sites:
- bh.org.il (site + shop)
- bh.org.il/jewish-spotlight/austria
- bh.org.il/jewish-spotlight/fiume

Remaining sites:
- nobel.bh.org.il (issue Beit-Hatfutsot/wp-nobel#3)
- leoncharney.bh.org.il

**Comment by nuritgazit** [comment]
@nirgoldberg what about http://spotlight.bh.org.il/czech/?

**Comment by nirgoldberg** [comment]
Spotlight will be updated as well (I'll open a separate issue for each of the remaining sites).

**Comment by nuritgazit** [comment]
@nirgoldberg @TheGrandVizier We are still missing the https for the noble winners site
